### ISSUE TITLE
Termux can't find any files or folders on "git clone" 

### ISSUE THREAD

**Issue by Dan1jel** [adi1090x/termux-desktop#26] opened 2020-11-10 11:03 UTC
This is what I got as reasons: 

`bash: ​git clone https://github.com/adi1090x/termux-desktop.git: No such file or directory`

![Screenshot_20201110-120115.png](https://user-images.githubusercontent.com/4266424/98666043-bec4fe80-234c-11eb-83f4-15c03ce18e4a.png)

**Comment by adi1090x** [comment] 2020-11-11 04:52
Works for me..., Is `git` installed?

![Screenshot_2020-11-10-21-16-31-332_com.termux.jpg](https://user-images.githubusercontent.com/26059688/98770208-b1207f00-2407-11eb-88ec-9343a001487f.jpg)

**Comment by Dan1jel** [comment] 2020-11-11 05:54
When trying to download my private, it works. Can't clone to my Raspberry either. ![Screenshot_20201111-063502.png](https://user-images.githubusercontent.com/4266424/98774191-cd61f300-23ea-11eb-84eb-84d728304937.png)

**Comment by RyanHutchison** [comment] 2020-11-12 02:27
I'm having the same issue here:
![Screenshot_20201111-202552_Termux.png](https://user-images.githubusercontent.com/7422225/98887810-40f01880-245c-11eb-9e9b-b72e76164760.png)

**Comment by RyanHutchison** [comment] 2020-11-12 02:58
So after closing exiting Termux, installing package-api, and x11-repo it was able to clone properly.

**Comment by Dan1jel** [comment] 2020-11-12 06:02
Try reinstall "termux-api" and "x11-repo" but that didn't work... [Screenshot_20201112-070145.png](https://user-images.githubusercontent.com/4266424/98901958-04044000-24b5-11eb-99d1-165337070a46.png)

**Comment by Dan1jel** [comment] 2020-11-12 22:01
Somehow when I copy text from your link it won't work in Termux, but when I type "git clone" followed with the URL from share button, it works. Don't know if this is Google Keyboard, Termux or Github app that is messing with the text/code.

[Watch my screen-recording](https://imgur.com/a/6DwOVPR)

**Comment by ZalgoNoise** [comment] 2020-11-14 21:18
The issue is that you are choosing the _Select All_ option which includes another character that's not interpreted by your shell.

See in `zsh`:
![zsh](https://imgur.com/35uAEpc.jpg)

### Workaround

As you did, avoid the Android's _Select All_ option and manually copy the command, or in this case just get the repo URL and clone it

**Comment by Dan1jel** [comment] 2020-11-14 21:47
> The issue is that you are choosing the _Select All_ option which includes another character that's not interpreted by your shell.
> 
> See in `zsh`:
> ![zsh](https://imgur.com/35uAEpc.jpg)
> 
> ### Workaround
> 
> As you did, avoid the Android's _Select All_ option and manually copy the command, or in this case just get the repo URL and clone it 

You are correct, i noticed this also when I tried zsh. And because of your explanation, this issue can now be closed (if you ask me). This is something I though only i had but it feels good to have another giving the answer.

**Closed** 2023-08-20 09:09 UTC
